@startuml
set separator none
title Knowledge Slipbox - Dynamic

left to right direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

Container_Boundary("DataFabric.KnowledgeSlipbox_boundary", "Knowledge Slipbox", $tags="") {
  Component(DataFabric.KnowledgeSlipbox.KnowledgeGraphDatabase, "Knowledge Graph Database", $techn="", $descr="Graph Database", $tags="", $link="")
  Component(DataFabric.KnowledgeSlipbox.KnowledgeSlipboxApiProvider, "Knowledge Slipbox Api Provider", $techn="", $descr="Knowledge Graph", $tags="", $link="")
}

Container_Boundary("DataFabric.ActiveMetadata_boundary", "Active Metadata", $tags="") {
  Component(DataFabric.ActiveMetadata.MetaGin, "Meta Gin", $techn="Active Metadata", $descr="Metadata Analyzer", $tags="", $link="")
  Component(DataFabric.ActiveMetadata.FabricDataCatalog, "Fabric Data Catalog", $techn="Active Metadata", $descr="Integrated Data Catalog", $tags="", $link="")
}

Container(DataFabric.Jotter, "Jotter", $techn="Data Fabric", $descr="Web Application", $tags="", $link="")
Container(DataFabric.FabricAPIProvider, "Fabric API Provider", $techn="Int2 Data Fabric", $descr="API", $tags="", $link="")

Rel_D(DataFabric.ActiveMetadata.MetaGin, DataFabric.ActiveMetadata.FabricDataCatalog, "1. fetch", $techn="", $tags="", $link="")
Rel_D(DataFabric.KnowledgeSlipbox.KnowledgeSlipboxApiProvider, DataFabric.KnowledgeSlipbox.KnowledgeGraphDatabase, "2. fetch", $techn="", $tags="", $link="")
Rel_D(DataFabric.FabricAPIProvider, DataFabric.KnowledgeSlipbox.KnowledgeSlipboxApiProvider, "3. ", $techn="", $tags="", $link="")
Rel_D(DataFabric.FabricAPIProvider, DataFabric.ActiveMetadata.MetaGin, "4. ", $techn="", $tags="", $link="")
Rel_D(DataFabric.Jotter, DataFabric.FabricAPIProvider, "5. use as Knowledge Catalog", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml