@startuml
set separator none
title Active Metadata - Dynamic

left to right direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

Container_Boundary("DataFabric.ActiveMetadata_boundary", "Active Metadata", $tags="") {
  Component(DataFabric.ActiveMetadata.MetaGin, "Meta Gin", $techn="Active Metadata", $descr="Metadata Analyzer", $tags="", $link="")
  Component(DataFabric.ActiveMetadata.ODDSpecification, "ODD Specification", $techn="Active Metadata", $descr="Data Catalog Schema", $tags="", $link="")
  Component(DataFabric.ActiveMetadata.FabricDataCatalog, "Fabric Data Catalog", $techn="Active Metadata", $descr="Integrated Data Catalog", $tags="", $link="")
}

Container(DataFabric.FabricBroker, "Fabric Broker", $techn="Int2 Data Fabric", $descr="Broker to manage data pipeline.", $tags="", $link="")

Rel_D(DataFabric.FabricBroker, DataFabric.ActiveMetadata.MetaGin, "2. access data source through Broker", $techn="", $tags="", $link="")
Rel_D(DataFabric.ActiveMetadata.MetaGin, DataFabric.ActiveMetadata.ODDSpecification, "3. analyze", $techn="", $tags="", $link="")
Rel_D(DataFabric.ActiveMetadata.ODDSpecification, DataFabric.ActiveMetadata.FabricDataCatalog, "4. convert", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml