@startuml
set separator none
title Active Metadata - Dynamic

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("DataFabric.KnowledgeSlipbox_boundary", "Knowledge Slipbox", $tags="") {
  Component(DataFabric.KnowledgeSlipbox.KnowledgeWeaver, "Knowledge Weaver", "Knowledge Weaver", $tags="")
  Component(DataFabric.KnowledgeSlipbox.KnowledgeGraphDatabase, "Knowledge Graph Database", "Graph Database", $tags="")
}

Container_Boundary("DataFabric.ActiveMetadata_boundary", "Active Metadata", $tags="") {
  Component(DataFabric.ActiveMetadata.MetaGin, "Meta Gin", "Active Metadata", "Metadata Analyzer", $tags="")
  Component(DataFabric.ActiveMetadata.ODDSpecification, "ODD Specification", "Active Metadata", "Data Catalog Schema", $tags="")
  Component(DataFabric.ActiveMetadata.FabricDataCatalog, "Fabric Data Catalog", "Active Metadata", "Integrated Data Catalog", $tags="")
}

System_Ext(DataLake, "Data Lake", "A type of data source, Data Lake.", $tags="")
System_Ext(DataWarehouse, "Data Warehouse", "A type of data source, Data Warehouse.", $tags="")
System_Ext(DataSource, "Data Source", "A type of data source in general.", $tags="")

Rel_D(DataLake, DataFabric.ActiveMetadata.ODDSpecification, "1. convert", $tags="")
Rel_D(DataWarehouse, DataFabric.ActiveMetadata.ODDSpecification, "2. convert", $tags="")
Rel_D(DataSource, DataFabric.ActiveMetadata.ODDSpecification, "3. convert", $tags="")
Rel_D(DataFabric.ActiveMetadata.ODDSpecification, DataFabric.ActiveMetadata.FabricDataCatalog, "4. convert", $tags="")
Rel_D(DataFabric.ActiveMetadata.MetaGin, DataFabric.ActiveMetadata.FabricDataCatalog, "5. analyze", $tags="")
Rel_D(DataFabric.KnowledgeSlipbox.KnowledgeWeaver, DataFabric.ActiveMetadata.MetaGin, "6. weave Knowledge from Metadata", $tags="")
Rel_D(DataFabric.KnowledgeSlipbox.KnowledgeWeaver, DataFabric.KnowledgeSlipbox.KnowledgeGraphDatabase, "7. build Local Knowledge Graph", $tags="")

SHOW_LEGEND(true)
@enduml