@startuml
set separator none
title System Landscape

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

AddElementTag("Software System", $bgColor="#1168bd", $borderColor="#0b4884", $fontColor="#ffffff", $sprite="", $shadowing="")
AddElementTag("Element", $bgColor="#dddddd", $borderColor="#9a9a9a", $fontColor="#000000", $sprite="", $shadowing="")
AddElementTag("Software System,Hycon", $bgColor="#ffd470", $borderColor="#b2944e", $fontColor="#4a4a4a", $sprite="", $shadowing="")

AddRelTag("Relationship", $textColor="#707070", $lineColor="#707070", $lineStyle = "")

skinparam svgDimensionStyle false
skinparam preserveAspectRatio meet
AddBoundaryTag("Distributed Datasets", $borderColor="#cccccc", $fontColor="#cccccc")
Boundary(group_1, "Distributed Datasets", $tags="Distributed Datasets") {
  Person(ERP, "ERP", $descr="Traditional type of dataset in enterprise grade.", $tags="Element", $link="")
  Person(DataLake, "Data Lake", $descr="Unstructured or semi-structured dataset", $tags="Element", $link="")
  Person(DataWarehouse, "Data Warehouse", $descr="Structured dataset.", $tags="Element", $link="")
    AddBoundaryTag("Distributed Datasets/Hycon Data Pipeline", $borderColor="#cccccc", $fontColor="#cccccc")
    Boundary(group_2, "Hycon Data Pipeline", $tags="Distributed Datasets/Hycon Data Pipeline") {
      Person(GeneratedDatabyScenarioDirectory, "Generated Data by Scenario Directory", $descr="Autonomous Driving Data for Machine Learning", $tags="Element", $link="")
      System(DataPipeline, "Data Pipeline", $descr="An autonomous driving dataset generated from scenarios provided by the consortium.", $tags="Software System,Hycon", $link="data-pipeline/context/")
    }

}

AddBoundaryTag("Int2 Data Fabric", $borderColor="#cccccc", $fontColor="#cccccc")
Boundary(group_3, "Int2 Data Fabric", $tags="Int2 Data Fabric") {
  System(DataFabric, "Data Fabric", $descr="Orchestrates distributed datasets owned by individual entities, enabling information retrieval and managing the data lifecycle.", $tags="Software System", $link="data-fabric/context/")
}

AddBoundaryTag("Stakeholders", $borderColor="#cccccc", $fontColor="#cccccc")
Boundary(group_4, "Stakeholders", $tags="Stakeholders") {
  Person(DataConsumer, "Data Consumer", $descr="A consumer who are needed a data in various context.", $tags="Element", $link="")
}


Rel_D(GeneratedDatabyScenarioDirectory, DataPipeline, "Transfer Data", $techn="", $tags="Relationship", $link="")
Rel_D(DataFabric, DataPipeline, "", $techn="", $tags="Relationship", $link="")
Rel_D(DataConsumer, DataFabric, "", $techn="", $tags="Relationship", $link="")
Rel_D(DataFabric, ERP, "", $techn="", $tags="Relationship", $link="")
Rel_D(DataFabric, DataLake, "", $techn="", $tags="Relationship", $link="")
Rel_D(DataFabric, DataWarehouse, "", $techn="", $tags="Relationship", $link="")

SHOW_LEGEND(true)
@enduml