@startuml
set separator none
title System Landscape

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

skinparam svgDimensionStyle false
skinparam preserveAspectRatio meet
AddBoundaryTag("Data Source", $borderColor="#cccccc", $fontColor="#cccccc")
Boundary(group_1, "Data Source", $tags="Data Source") {
}

AddBoundaryTag("Int2 Data Fabric", $borderColor="#cccccc", $fontColor="#cccccc")
Boundary(group_2, "Int2 Data Fabric", $tags="Int2 Data Fabric") {
  System(DataFabric, "Data Fabric", $descr="Weaving together structured and contextualized knowledge from diverse sources.", $tags="", $link="data-fabric/context/")
}

AddBoundaryTag("Stakeholders", $borderColor="#cccccc", $fontColor="#cccccc")
Boundary(group_3, "Stakeholders", $tags="Stakeholders") {
  Person(DataConsumer, "Data Consumer", $descr="A consumer who are needed a data in various context.", $tags="", $link="")
  Person(DataOwner, "Data Owner", $descr="A provider who owned data set.", $tags="", $link="")
}


Rel_D(DataConsumer, DataFabric, "fetch data", $techn="", $tags="", $link="")
Rel_D(DataFabric, DataOwner, "data pipeline", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml